const data = {
  products: [
    {
      name: 'Galaxy A03',
      slug: 'galaxy-a03',
      category: 'Smartphones',
      image: '/images/p1.jpg', // 280px x 280px
      price: 39990.0,
      countInStock: 5,
      brand: 'Samsung',
      rating: 4.5,
      numReviews: 6,
      description: 'Description 1',
    },
    {
      name: 'Galaxy A03 Core',
      slug: 'galaxy-a03-core',
      category: 'Smartphones',
      image: '/images/p2.jpg',
      price: 39990.0,
      countInStock: 7,
      brand: 'Samsung',
      rating: 4.6,
      numReviews: 10,
      description: 'Description 2',
    },
    {
      name: 'Galaxy A03s',
      slug: 'galaxy-a03s',
      category: 'Smartphones',
      image: '/images/p3.jpg',
      price: 46990.0,
      countInStock: 2,
      brand: 'Samsung',
      rating: 4.9,
      numReviews: 12,
      description: 'Description 3',
    },
    {
      name: 'Galaxy A12',
      slug: 'galaxy-a12',
      category: 'Smartphones',
      image: '/images/p4.jpg',
      price: 51990.0,
      countInStock: 1,
      brand: 'Samsung',
      rating: 5.0,
      numReviews: 13,
      description: 'Description 4',
    },
  ],
};
export default data;
